### ISSUE TITLE
add ability to fail check if benchmark regression is outside range

### ISSUE THREAD

**Issue by bonedaddy** [bobheadxi/gobenchdata#28]
While reading /r/Golang I noticed a new post about [cob](https://github.com/knqyf263/cob), which is a continuous benchmark tool focused on performing checks during PR or commit builds with TravisCI, GitHub Actions, and CircleCI to see if there is regression in benchmark performance outside of an acceptable range. If the regression is outside of a certain range, then the CI build will fail. It might be useful to integrate this kind of functionality within `gobenchdata`. If so I can take a stab at implementing it.

**Comment by bobheadxi** [comment]
Yep! I was thinking the exact same thing when I opened #27 😛 I'll close that one in favour of this.

If you want to take a stab at implementing this please go ahead! The only thought I have on this is leveraging the "database" that `gobenchdata` continuously creates (i.e. https://github.com/bobheadxi/gobenchdata/blob/gh-pages/benchmarks.json) to make comparisons.

**Comment by bonedaddy** [comment]
Sounds good, I will start poking around with this in the morning :rocket:
