### ISSUE TITLE
Option to have graph for each benchmark

### ISSUE THREAD

**Issue by JRascagneres** [bobheadxi/gobenchdata#29]
The per-package graphs work well for scenarios such as the one used for the demo web app however in the case where there many more benchmarks the graphs don't scale well. As shown in this screenshot:
![image](https://user-images.githubusercontent.com/3264971/74736799-6f352480-524b-11ea-8ae5-2a8282b3ad09.png)

I'd like to be able to generate a web app to display a graph for each benchmark individually. If you're happy for this to be an option I'd be happy to work on a PR.

**Comment by bobheadxi** [comment]
Yeah my current implementation definitely assumes you don't have an awful lot of benchmarks, but a mechanism to group/distribute the benchmarks across different graphs would be great! I'm open to whatever design you have in mind and would love a PR!

**Comment by bobheadxi** [comment]
Closed by #30, and I've cut a [new release](https://github.com/bobheadxi/gobenchdata/releases/tag/v0.5.0) with this feature. Thank you @JRascagneres !
