### ISSUE TITLE
Infinite loop when using it in on: pull_request

### ISSUE THREAD

**Issue by hazcod** [bobheadxi/gobenchdata#43]
Hi, I have an issue in https://github.com/ironpeakservices/iron-go-project/pull/11 where it will keep committing new benchmarks, which will commit a new benchmark, which triggers the Action again.

**Comment by bobheadxi** [comment]
Ah, yeah if you don't use the GitHub Actions actor (`GITHUB_ACTOR`) which is available in an Action run, new commits can trigger new builds.

Unfortunately this can't really be resolved by gobenchdata - you'll have to either:

* use the default actor, such that the commit shows author shows up like [this](https://github.com/sourcegraph/sourcegraph/pull/11616/commits/ac301530b234d3e82e79a22a1c5f7ddfa36cee44) (sorry dont have a gobenchdata-relevant example)
* push to an alternative branch or repo, like `gh-pages`

**Comment by bobheadxi** [comment]
Hey, closing this for now - this seems to be more of a usage issue :) Let me know if you have any other problems!
