### ISSUE TITLE
Clicking on chart doesn't open commit version

### ISSUE THREAD

**Issue by josephgardner** [bobheadxi/gobenchdata#61]
I've updated my template to version 1.1.0 by re-running generate,

```sh
gobenchdata web generate .
```
However clicking points on the graph no longer launches the repo URL. 

Running `serve` exhibits the same behavior,

```sh
gobenchdata web serve
```

Are changes to the config required to upgrade the web template?

**Comment by bobheadxi** [comment]
Hey! Do you mind sharing your config so I can attempt to reproduce?

**Comment by josephgardner** [comment]
I'll try to reproduce with a fresh install and report back.

**Comment by bobheadxi** [comment]
I was able to reproduce this actually, investigating!

**Comment by bobheadxi** [comment]
Should be fixed by https://github.com/bobheadxi/gobenchdata/commit/be312a9986f47794b08d85f4481253d5d0a0945e :)
