### ISSUE TITLE
failing benchmarks ignored

### ISSUE THREAD

**Issue by srenatus** [bobheadxi/gobenchdata#69]
I've just observed this locally:

```
$ go test -run=- -bench=BenchmarkMonster ./pkg/rego_vm 
--- FAIL: BenchmarkMonster
    monster_test.go:125: open monster.rego: no such file or directory
FAIL
exit status 1
FAIL    github.com/some/monster    0.230s
FAIL
$ echo $?
1
$ go test -run=- -bench=BenchmarkMonster ./pkg/rego_vm | gobenchdata --json test.json -v version
detected 0 benchmark suites
successfully output results as json to 'test.json'
```

So one obvious workaround is to add a test stage that'll run the benchmarks _before_ the gobenchdata run. It would mean we run the benchmarks twice.

An alternative might be to [add `pipefail` to the `set` line](https://github.com/bobheadxi/gobenchdata/blob/main/entrypoint.sh#L2) in entrypoint.sh?

Another alternative would be to have the action consume a file, so we could run the benchmarks once manually, save the result, and feed the result into gobenchdata.

What do you think?

**Comment by bobheadxi** [comment]
I think `pipefail` is probably the right way to go - errors anywhere in the process should cause the whole action to fail I think

**Comment by srenatus** [comment]
Thank you! I've been meaning to do this PR eventually but it fell off my radar today.

**Comment by bobheadxi** [comment]
Sorry to take it from you, wanted to include it in this release :) Thanks for reporting it!

**Comment by srenatus** [comment]
Ha no worries. I'm glad it's sorted.
